FROM n8nio/n8n

# OPTIONAL: Set up basic auth for the n8n UI
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=yourpassword

# OPTIONAL: Disable telemetry
ENV N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
ENV N8N_DIAGNOSTICS_ENABLED=false
